<a href="https://colab.research.google.com/github/Ankit-ally/Ankit-ally/blob/main/nlptext.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
url="https://raw.githubusercontent.com/nethajinirmal13/Training-datasets/main/train_tweets.csv"
import pandas as pd
df=pd.read_csv(url)
display(df)

          id  label                                              tweet
0          1      0   @user when a father is dysfunctional and is s...
1          2      0  @user @user thanks for #lyft credit i can't us...
2          3      0                                bihday your majesty
3          4      0  #model   i love u take with u all the time in ...
4          5      0             factsguide: society now    #motivation
...      ...    ...                                                ...
31957  31958      0  ate @user isz that youuu?ðððððð...
31958  31959      0    to see nina turner on the airwaves trying to...
31959  31960      0  listening to sad songs on a monday morning otw...
31960  31961      1  @user #sikh #temple vandalised in in #calgary,...
31961  31962      0                   thank you @user for you follow

[31962 rows x 3 columns]

In [ ]:
df_text=df[['tweet']].copy()
df_text.head()

                                               tweet
0   @user when a father is dysfunctional and is s...
1  @user @user thanks for #lyft credit i can't us...
2                                bihday your majesty
3  #model   i love u take with u all the time in ...
4             factsguide: society now    #motivation

In [ ]:
# for lower case ##
sample_sentence = "This is a Sample Sentence."
lower_case_sentence = sample_sentence.lower()
print(lower_case_sentence)

this is a sample sentence.

In [ ]:

df_text['tweet']=df_text['tweet'].str.lower()
df_text.head()

/tmp/ipykernel_167/3372412739.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_text['tweet']=df_text['tweet'].str.lower()

                                               tweet
0   @user when a father is dysfunctional and is s...
1  @user @user thanks for #lyft credit i can't us...
2                                bihday your majesty
3  #model   i love u take with u all the time in ...
4             factsguide: society now    #motivation

In [ ]:
def remove_whitespace(text):
  return  " ".join(text.split())




# Test
text = "     We      will        going to win this match"
remove_whitespace(text)

'We will going to win this match'

In [ ]:
df_text.loc[:, 'tweet']=df_text['tweet'].apply(remove_whitespace)

In [ ]:
display(df_text)

                                                   tweet
0      @user when a father is dysfunctional and is so...
1      @user @user thanks for #lyft credit i can't us...
2                                    bihday your majesty
3      #model i love u take with u all the time in ur...
4                    factsguide: society now #motivation
...                                                  ...
31957  ate @user isz that youuu?ðððððð...
31958  to see nina turner on the airwaves trying to w...
31959  listening to sad songs on a monday morning otw...
31960  @user #sikh #temple vandalised in in #calgary,...
31961                     thank you @user for you follow

[31962 rows x 1 columns]

In [ ]:
import nltk
nltk.download('punkt')




import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [ ]:
from nltk import word_tokenize
toketest="!@#$%^&*iste datasciece etc etc"
a=word_tokenize(toketest)
a

['!', '@', '#', '$', '%', '^', '&', '*', 'iste', 'datasciece', 'etc', 'etc']

In [ ]:
from nltk import word_tokenize
df_text['tweet']=df_text['tweet'].apply(lambda X: word_tokenize(X))

In [ ]:
df_text.head()

                                               tweet
0  [@, user, when, a, father, is, dysfunctional, ...
1  [@, user, @, user, thanks, for, #, lyft, credi...
2                            [bihday, your, majesty]
3  [#, model, i, love, u, take, with, u, all, the...
4       [factsguide, :, society, now, #, motivation]

In [ ]:
!pip install pyspellchecker

Collecting pyspellchecker
  Downloading pyspellchecker-0.9.0-py3-none-any.whl.metadata (9.3 kB)
Downloading pyspellchecker-0.9.0-py3-none-any.whl (7.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.2/7.2 MB 31.1 MB/s eta 0:00:00
Installing collected packages: pyspellchecker
Successfully installed pyspellchecker-0.9.0

In [ ]:
from spellchecker import SpellChecker
def spell_check(text):




  result = []
  spell = SpellChecker()
  for word in text:
      correct_word = spell.correction(word)
      result.append(correct_word)




  return result




#Test
text = "i like india godd vry psyholgy vercity  lethoogia mch milion of recalctrnt".split()
spell_check(text)

['i',
 'like',
 'india',
 'good',
 'very',
 'psychology',
 'veracity',
 None,
 'much',
 'million',
 'of',
 'recalcitrant']

In [ ]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
print(stopwords.words('english'))

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [ ]:
en_stopwords = stopwords.words('english')

def remove_stopwords(text):
  result = []
  for token in text:
    if token not in en_stopwords:
      result.append(token)
  return result

In [ ]:
#Test
test_sentence = "this is the only solution of that question".split()
print(remove_stopwords(test_sentence))

df_text['tweet'] = df_text['tweet'].apply(remove_stopwords)
df_text.head()

['solution', 'question']

                                               tweet
0  [@, user, father, dysfunctional, selfish, drag...
1  [@, user, @, user, thanks, #, lyft, credit, ca...
2                                  [bihday, majesty]
3  [#, model, love, u, take, u, time, urð±, !, ...
4            [factsguide, :, society, #, motivation]

In [ ]:
df_text['tweet'] = df_text['tweet'].apply(spell_check)
df_text.head()

In [ ]:

#Punctuations
from nltk.tokenize import RegexpTokenizer




def remove_punct(text):




  tokenizer = RegexpTokenizer(r"\w+")
  lst=tokenizer.tokenize(' '.join(text))
  return lst




#Test
text=df_text['tweet'][0]
print(text)
remove_punct(text)

In [ ]:
#TAGS


import re
def remove_tag(text):




  text=' '.join(text)
  html_pattern = re.compile('<.*?>')
  return html_pattern.sub(r'', text)




#Test
text = "<HEAD> this is head tag </HEAD>"
remove_tag(text.split())

In [ ]:

df_text['tweet'] = df_text['tweet'].apply(remove_tag)
df_text.head()

In [ ]:
#URLs


def remove_urls(text):
  url_pattern = re.compile(r'https?://\S+|www\.\S+')
  return url_pattern.sub(r'', text)




#Test
text = "Machine learning knowledge is an awsome site. Here is the link for it https://machinelearningknowledge.ai/"
remove_urls(text)

In [ ]:
df_text['tweet'] = df_text['tweet'].apply(remove_urls)
df_text.head()

In [ ]:
from nltk.stem import WordNetLemmatizer
from nltk import word_tokenize,pos_tag
import nltk
nltk.download('averaged_perceptron_tagger')
nltk.download('wordnet')
import nltk
nltk.download('averaged_perceptron_tagger_eng')
def lemmatization(text):


   result=[]
   wordnet = WordNetLemmatizer()
   for token,tag in pos_tag(text):
       pos=tag[0].lower()


       if pos not in ['a', 'r', 'n', 'v']:
           pos='n'


       result.append(wordnet.lemmatize(token,pos))


   return result


#Test
text = ['running','ran','runs']
lemmatization(text)

In [ ]:
df_text['tweet']=df_text['tweet'].apply(lemmatization)
df_text.head()

In [ ]:
import nltk
nltk.download('omw-1.4')

In [ ]:
from nltk.stem import PorterStemmer


def stemming(text):
   porter = PorterStemmer()


   result=[]
   for word in text:

In [ ]:
       result.append(porter.stem(word))
   return result


#Test
text=['Connects','Connecting','Connections','Connected','Connection','Connectings','Connect']
stemming(text)

In [ ]:
df_text['tweet']=df_text['tweet'].apply(stemming)
df_text.head()

In [1]:
import pandas as pd
import numpy as np
import collections

In [2]:

doc1 = 'Game of Thrones is an amazing tv series!'
doc2 = 'Game of Thrones is the best tv series!'
doc3 = 'Game of of Thrones is so great'

In [3]:

from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
X = vectorizer.fit_transform([doc1,doc2,doc3])
df_bow_sklearn = pd.DataFrame(X.toarray(),columns=vectorizer.get_feature_names_out())
df_bow_sklearn.head()

   amazing  an  best  game  great  is  of  series  so  the  thrones  tv
0        1   1     0     1      0   1   1       1   0    0        1   1
1        0   0     1     1      0   1   1       1   0    1        1   1
2        0   0     0     1      1   1   2       0   1    0        1   0

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
#corpus = ['Text processing is necessary.', 'Text processing is necessary and important.', 'Text processing is easy.']
corpus=[doc1,doc2,doc3]
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names_out())
print(X)

['amazing' 'an' 'best' 'game' 'great' 'is' 'of' 'series' 'so' 'the'
 'thrones' 'tv']
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 22 stored elements and shape (3, 12)>
  Coords	Values
  (0, 3)	1
  (0, 6)	1
  (0, 10)	1
  (0, 5)	1
  (0, 1)	1
  (0, 0)	1
  (0, 11)	1
  (0, 7)	1
  (1, 3)	1
  (1, 6)	1
  (1, 10)	1
  (1, 5)	1
  (1, 11)	1
  (1, 7)	1
  (1, 9)	1
  (1, 2)	1
  (2, 3)	1
  (2, 6)	2
  (2, 10)	1
  (2, 5)	1
  (2, 8)	1
  (2, 4)	1

In [5]:
print(X.toarray())

[[1 1 0 1 0 1 1 1 0 0 1 1]
 [0 0 1 1 0 1 1 1 0 1 1 1]
 [0 0 0 1 1 1 2 0 1 0 1 0]]

In [6]:

from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)
print(X.toarray())

[[0.46869865 0.46869865 0.         0.27682097 0.         0.27682097
  0.27682097 0.3564574  0.         0.         0.27682097 0.3564574 ]
 [0.         0.         0.46869865 0.27682097 0.         0.27682097
  0.27682097 0.3564574  0.         0.46869865 0.27682097 0.3564574 ]
 [0.         0.         0.         0.28023746 0.47448327 0.28023746
  0.56047493 0.         0.47448327 0.         0.28023746 0.        ]]

In [ ]:

#Case study for NLP + ML

!wget https://drive.google.com/uc?id=1XDzkmJ4g9P9buUjXEwzD7RxDgQ5BEFKI

In [ ]:
!unzip /content/uc?id=1XDzkmJ4g9P9buUjXEwzD7RxDgQ5BEFKI

Archive:  /content/uc?id=1XDzkmJ4g9P9buUjXEwzD7RxDgQ5BEFKI
replace test.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename:

In [ ]:
import pandas as pd
# Local directory
Reviewdata = pd.read_csv('/content/train.csv')

In [ ]:
### Checking Missing values in the Data Set and printing the Percentage for Missing Values for Each Columns ###


count = Reviewdata.isnull().sum().sort_values(ascending=False)
percentage = ((Reviewdata.isnull().sum()/len(Reviewdata)*100)).sort_values(ascending=False)
missing_data = pd.concat([count, percentage], axis=1,
keys=['Count','Percentage'])


print('Count and percentage of missing values for the columns:')


missing_data